volumes:
  mariadb_data:

services:
  mariadb:
    image: mariadb:lts
    container_name: mariadb
    hostname: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql:rw
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
      - MARIADB_USER=chatinterface_server
      - MARIADB_DATABASE=chatinterface_server
      - MARIADB_PASSWORD=helloworld
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
  chatinterface_server:
    image: ghcr.io/newguy103/chatinterface-server:latest
    # build:
    #   context: ..
    #   dockerfile: docker/Dockerfile
    container_name: chatinterface_server
    volumes:
      - ./chatinterface_server:/app/chatinterface-server_config:rw
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT=3306
      - MARIADB_DBNAME=chatinterface_server
      - MARIADB_USER=chatinterface_server
      - MARIADB_PASSWORD=helloworld
      - ENVIRONMENT=production
    ports:
      - 8000:8000
    depends_on:
      mariadb:
        condition: service_healthy
