"""Remove UserChatRelations

Revision ID: 2cde6b73ab54
Revises: dc673a2dfa74
Create Date: 2025-05-04 16:41:53.512944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2cde6b73ab54'
down_revision: Union[str, None] = 'dc673a2dfa74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userchatrelations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userchatrelations',
    sa.Column('sender_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('recipient_id', mysql.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.user_id'], name='userchatrelations_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], name='userchatrelations_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sender_id'),
    mariadb_collate='utf8mb4_uca1400_ai_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    # ### end Alembic commands ###
