USER_EXISTS = "USER_EXISTS"
NO_USER = "NO_USER"

INVALID_TOKEN = "INVALID_TOKEN"
INVALID_DATETIME = "INVALID_DATETIME"

DATE_EXPIRED = "DATE_EXPIRED"
INVALID_SESSION = "INVALID_SESSION"

NO_SENDER = "NO_SENDER"
NO_RECIPIENT = "NO_RECIPIENT"

INVALID_MESSAGE = "INVALID_MESSAGE"
